# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'command.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Command(object):
    def setupUi(self, Command):
        Command.setObjectName("Command")
        Command.resize(434, 77)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Command.sizePolicy().hasHeightForWidth())
        Command.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(Command)
        self.gridLayout.setObjectName("gridLayout")
        self.nbcharLab = QtWidgets.QLabel(Command)
        self.nbcharLab.setObjectName("nbcharLab")
        self.gridLayout.addWidget(self.nbcharLab, 1, 2, 1, 1)
        self.commandLEdit = QtWidgets.QLineEdit(Command)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLEdit.sizePolicy().hasHeightForWidth())
        self.commandLEdit.setSizePolicy(sizePolicy)
        self.commandLEdit.setSizeIncrement(QtCore.QSize(0, 0))
        self.commandLEdit.setObjectName("commandLEdit")
        self.gridLayout.addWidget(self.commandLEdit, 0, 0, 1, 3)
        self.byteLabel = QtWidgets.QLabel(Command)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.byteLabel.sizePolicy().hasHeightForWidth())
        self.byteLabel.setSizePolicy(sizePolicy)
        self.byteLabel.setSizeIncrement(QtCore.QSize(1, 0))
        self.byteLabel.setObjectName("byteLabel")
        self.gridLayout.addWidget(self.byteLabel, 1, 0, 1, 1)
        self.crlfCBox = QtWidgets.QComboBox(Command)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.crlfCBox.sizePolicy().hasHeightForWidth())
        self.crlfCBox.setSizePolicy(sizePolicy)
        self.crlfCBox.setMinimumContentsLength(0)
        self.crlfCBox.setObjectName("crlfCBox")
        self.crlfCBox.addItem("")
        self.crlfCBox.addItem("")
        self.crlfCBox.addItem("")
        self.crlfCBox.addItem("")
        self.crlfCBox.addItem("")
        self.crlfCBox.setItemText(4, "")
        self.gridLayout.addWidget(self.crlfCBox, 1, 3, 1, 1)
        self.sendButton = QtWidgets.QPushButton(Command)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendButton.sizePolicy().hasHeightForWidth())
        self.sendButton.setSizePolicy(sizePolicy)
        self.sendButton.setObjectName("sendButton")
        self.gridLayout.addWidget(self.sendButton, 0, 3, 1, 1)
        self.cancelButton = QtWidgets.QToolButton(Command)
        icon = QtGui.QIcon.fromTheme("Ressource\\trash.png")
        self.cancelButton.setIcon(icon)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 0, 4, 1, 1)
        self.gridLayout.setColumnStretch(0, 90)

        self.retranslateUi(Command)
        QtCore.QMetaObject.connectSlotsByName(Command)

    def retranslateUi(self, Command):
        _translate = QtCore.QCoreApplication.translate
        Command.setWindowTitle(_translate("Command", "Form"))
        self.nbcharLab.setText(_translate("Command", "x caractères"))
        self.byteLabel.setText(_translate("Command", "TextLabel"))
        self.crlfCBox.setItemText(0, _translate("Command", "CR+LF"))
        self.crlfCBox.setItemText(1, _translate("Command", "CR"))
        self.crlfCBox.setItemText(2, _translate("Command", "LF"))
        self.crlfCBox.setItemText(3, _translate("Command", "Pas de CR+LF"))
        self.sendButton.setText(_translate("Command", "Envoyer"))
        self.cancelButton.setText(_translate("Command", "..."))
