# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtFiles/Logger.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Logger(object):
    def setupUi(self, Logger):
        Logger.setObjectName("Logger")
        Logger.resize(1271, 887)
        self.verticalLayout = QtWidgets.QVBoxLayout(Logger)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(Logger)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.encodingCBox = QtWidgets.QComboBox(Logger)
        self.encodingCBox.setObjectName("encodingCBox")
        self.encodingCBox.addItem("")
        self.encodingCBox.addItem("")
        self.encodingCBox.addItem("")
        self.horizontalLayout.addWidget(self.encodingCBox)
        self.label = QtWidgets.QLabel(Logger)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.crlfCBox = QtWidgets.QComboBox(Logger)
        self.crlfCBox.setObjectName("crlfCBox")
        self.crlfCBox.addItem("")
        self.crlfCBox.addItem("")
        self.crlfCBox.addItem("")
        self.crlfCBox.addItem("")
        self.horizontalLayout.addWidget(self.crlfCBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.saveButton = QtWidgets.QPushButton(Logger)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.eraseButton = QtWidgets.QPushButton(Logger)
        self.eraseButton.setObjectName("eraseButton")
        self.horizontalLayout.addWidget(self.eraseButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.logBrowser = QtWidgets.QTextBrowser(Logger)
        self.logBrowser.setObjectName("logBrowser")
        self.verticalLayout.addWidget(self.logBrowser)

        self.retranslateUi(Logger)
        QtCore.QMetaObject.connectSlotsByName(Logger)

    def retranslateUi(self, Logger):
        _translate = QtCore.QCoreApplication.translate
        Logger.setWindowTitle(_translate("Logger", "Form"))
        self.label_2.setText(_translate("Logger", "Encodage :"))
        self.encodingCBox.setItemText(0, _translate("Logger", "UTF-8"))
        self.encodingCBox.setItemText(1, _translate("Logger", "ASCII"))
        self.encodingCBox.setItemText(2, _translate("Logger", "HEX"))
        self.label.setText(_translate("Logger", "Ajouter à la fin :"))
        self.crlfCBox.setItemText(0, _translate("Logger", "Pas de CR+LF"))
        self.crlfCBox.setItemText(1, _translate("Logger", "AUTO CR+LF"))
        self.crlfCBox.setItemText(2, _translate("Logger", "AUTO CR"))
        self.crlfCBox.setItemText(3, _translate("Logger", "AUTO LF"))
        self.saveButton.setText(_translate("Logger", "Sauvegarder"))
        self.eraseButton.setText(_translate("Logger", "Effacer"))
