# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setSizeIncrement(QtCore.QSize(1, 1))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.topLayout = QtWidgets.QHBoxLayout()
        self.topLayout.setObjectName("topLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.topLayout.addWidget(self.label)
        self.portCBox = QtWidgets.QComboBox(self.centralwidget)
        self.portCBox.setObjectName("portCBox")
        self.topLayout.addWidget(self.portCBox)
        self.refreshButton = QtWidgets.QPushButton(self.centralwidget)
        self.refreshButton.setObjectName("refreshButton")
        self.topLayout.addWidget(self.refreshButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.topLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.topLayout)
        self.logLayout = QtWidgets.QHBoxLayout()
        self.logLayout.setContentsMargins(0, -1, 0, -1)
        self.logLayout.setObjectName("logLayout")
        self.commandLayout = QtWidgets.QVBoxLayout()
        self.commandLayout.setContentsMargins(0, 0, 0, 0)
        self.commandLayout.setSpacing(0)
        self.commandLayout.setObjectName("commandLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.commandLayout.addItem(spacerItem1)
        self.addCmdButton = QtWidgets.QPushButton(self.centralwidget)
        self.addCmdButton.setObjectName("addCmdButton")
        self.commandLayout.addWidget(self.addCmdButton)
        self.logLayout.addLayout(self.commandLayout)
        self.logger = Logger(self.centralwidget)
        self.logger.setObjectName("logger")
        self.logLayout.addWidget(self.logger)
        self.logLayout.setStretch(0, 50)
        self.logLayout.setStretch(1, 50)
        self.verticalLayout_3.addLayout(self.logLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Port COM : "))
        self.refreshButton.setText(_translate("MainWindow", "Rafraichir"))
        self.addCmdButton.setText(_translate("MainWindow", "Ajouter une commande"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
from Logger import Logger
